services:
    _defaults:
        autoconfigure: true
        autowire: true

    Symfony\Component\Routing\Loader\AnnotationDirectoryLoader:
        arguments:
            $locator: '@file_locator'
            $reader: '@annotation_reader'
        tags: ['routing.loader']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    JBSupport\MultipleSitemapsBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Resources}'

    JBSupport\MultipleSitemapsBundle\Routing\RegisterSitemapRoutes:
        tags:
            - { name: routing.loader }